/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CustomSnackBar: typeof import('./src/components/snackbars/CustomSnackBar.vue')['default']
    DashBoradTest: typeof import('./src/components/DashBoradTest.vue')['default']
    DeleteDialog: typeof import('./src/components/Dialog/DeleteDialog.vue')['default']
    EssayCard: typeof import('./src/components/EssayShow/EssayCard.vue')['default']
    EssayEditor: typeof import('./src/components/EssayEditor.vue')['default']
    EssayHomePage: typeof import('./src/components/EssayShow/EssayHomePage.vue')['default']
    Essays: typeof import('./src/components/Essays.vue')['default']
    HomePage: typeof import('./src/components/HomePage.vue')['default']
    Login: typeof import('./src/components/Login.vue')['default']
    RichText: typeof import('./src/components/RichText/RichText.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserAdminstration: typeof import('./src/components/UserAdminstration.vue')['default']
    UserRegister: typeof import('./src/components/Users/UserRegister.vue')['default']
  }
}
